steps:
- name: 'rust:1.33-slim'
  id: Test
  entrypoint: /bin/sh
  args:
  - -c
  - 'cargo test'

- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA'
  - '.'
 
images: ['gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA']
