steps:
- name: 'gcr.io/cloud-builders/docker'
  id: Test
  args:
  - 'build'
  - '--file'
  - 'Dockerfile.test'
  - '.'

- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA'
  - '.'

images: ['gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA']
timeout: 1800s
